apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-fruit-services
  namespace: genai
  labels:
    app: mcp-fruit-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-fruit-services
  template:
    metadata:
      labels:
        app: mcp-fruit-services
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      containers:
      - name: mcp-fruit-services
        image: public.ecr.aws/p7b6k2h9/fmamazon/genai-eks:python-3.11-slim
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - NET_RAW
          seccompProfile:
            type: RuntimeDefault
        command: ["/bin/sh", "-c"]
        args:
        - >
          mkdir -p /app &&
          pip install fastapi langgraph langchain-openai langchain-mcp-adapters fastapi uvicorn &&
          cp /config/mcp-fruit-prices.py /app/ &&
          cd /app &&
          python mcp-fruit-prices.py
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: mcp-fruit-prices-config
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-fruit-services
  namespace: genai
spec:
  selector:
    app: mcp-fruit-services
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
